# Generated by Django 5.0.2 on 2024-02-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lipanampesa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PushedSTKs',
        ),
    ]
