# Generated by Django 5.0.2 on 2024-02-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberdetails',
            name='created',
        ),
        migrations.AddField(
            model_name='memberdetails',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
